env:
  node: true
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  quotes: [error, single, { allowTemplateLiterals: true }],
  no-console: [warn],
  '@typescript-eslint/indent': off,
  '@typescript-eslint/semi': [2, always],
  '@typescript-eslint/no-var-requires': off,
  '@typescript-eslint/no-unused-vars': off,
  '@typescript-eslint/no-non-null-assertion': off
}
